#pragma once

/* Drive ports */
#define RIGHT_FRONT_PORT 4
#define RIGHT_BACK_PORT 5
#define LEFT_FRONT_PORT 6
#define LEFT_BACK_PORT 7

/* Launcher Ports */
#define FRONT_WINCH_PORT 11
#define BACK_WINCH_PORT 12

/* Solenoids */
#define LEFT_DRIVE_SHIFTER_PCM 2
#define RIGHT_DRIVE_SHIFTER_PCM 2
#define COMPRESSOR_PCM 2
#define WINCH_PCM 2
#define LEFT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7
#define RIGHT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7 
#define LEFT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define RIGHT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define DOG_SHIFTER_PISTON_OUT_PORT 8
#define DOG_SHIFTER_PISTON_IN_PORT 9
#define RELEASE_PISTON_OUT_PORT 10
#define RELEASE_PISTON_IN_PORT 11

