#pragma once

/* Drive ports */
#define RIGHT_FRONT_PORT 20
#define RIGHT_BACK_PORT 14
#define LEFT_FRONT_PORT 19
#define LEFT_BACK_PORT 32

/* Launcher Ports */
#define WINCH_PORT 32

/* Solenoids */
#define LEFT_DRIVE_SHIFTER_PCM 2
#define RIGHT_DRIVE_SHIFTER_PCM 2
#define COMPRESSOR_PCM 2
#define WINCH_PCM 2
#define LEFT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7
#define RIGHT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7 
#define LEFT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define RIGHT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define WINCH_PISTON_OUT_PORT 8
#define WINCH_PISTON_IN_PORT 9

